apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-volume-claim
  namespace: nexus
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nexus"