apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-keycloak-postgresql-0
  namespace: keycloak
  labels:
    type: local
spec:
  storageClassName: standart
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/keycloak"