kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-keycloak-postgresql-0
  namespace: keycloak
spec:
  storageClassName: standart
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi