  - name: Separately update the repository cache
    kubernetes.core.helm:
      name: dummy
      namespace: kube-system
      state: absent
      update_repo_cache: true
  - name: Nexus key create
    command: |
      kubectl create secret tls {{ nexus.tls.Name }} \
      --cert=roles/common/templates/{{ nexus.tls.CrtName }} \
      --key=roles/common/templates/{{ nexus.tls.KeyName }}
    ignore_errors: true
  - name: Keycloak key create
    command: |
      kubectl create secret tls {{ keycloak.tls.Name }} \
      --cert=roles/common/templates/{{ keycloak.tls.CrtName }} \
      --key=roles/common/templates/{{ keycloak.tls.KeyName }}
    ignore_errors: true